//
//  listOfWords.swift
//  ApplePie
//
//  Created by Ahmed Elsayed on 03/08/2023.
//

import Foundation

let listOfWords = [
    "buccaneer", "swift", "glorious", "incandescent", "bug", "program",
    "vexed", "captivate", "catastrophe", "iridescent", "magnificent",
    "jubilant", "spectacular", "colossal", "quizzical", "extravagant",
    "exuberant", "fascinate", "mellifluous", "zephyr", "effervescent",
    "whimsical", "preposterous", "wonderful", "benevolent", "luminous",
    "grandiose", "serendipity", "enigmatic", "murmuration", "resplendent",
    "effulgent", "melancholy", "quintessential", "bewilder", "vivacious",
    "nurturing", "conundrum", "effervescent", "labyrinth", "evanescent",
    "ephemeral", "enchanting", "effulgent", "iridescence", "phenomenal",
    "splendiferous", "cynosure", "ebullient", "luminosity", "efflorescence",
    "capricious", "resilient", "enigmatic", "surreptitious", "breathtaking",
    "sensational", "effervescent", "lackadaisical", "flabbergasted", "serene",
    "magnanimous", "petrichor", "perpendicular", "astounding", "diaphanous",
    "mellifluous", "belligerent", "scintillating", "whimsical", "vibrant",
    "effulgence", "evanescence", "resonate", "melodious", "labyrinthine",
    "ebullience", "benevolence", "effervescence", "captivating", "enrapture",
    "magnificence", "flummox", "bucolic", "iridescent", "resplendence",
    "effortless", "languorous", "opulence", "cogent", "efficacious",
    "scrumptious", "effulgent", "enchant", "resplendent", "magniloquent",
    "whimsical", "breathtaking", "scintillate", "exquisite", "mellifluous",
    "benevolence", "effulgence", "captivating", "enrapture", "magnificence",
    "effervescent", "resonate", "melodious", "labyrinthine", "ebullience",
    "buccaneer", "swift", "glorious", "incandescent", "bug", "program",
    "frivolous", "exemplary", "belligerent", "indefatigable", "serendipity",
    "zephyr", "quintessential", "magnificent", "effulgence", "opulent",
    "ebullient", "labyrinth", "resplendent", "mellifluous", "whimsical",
    "vibrant", "enchanting", "effervescent", "iridescent", "bucolic",
    "spectacular", "preposterous", "murmuration", "splendiferous", "jubilant",
    "efficacious", "benevolent", "quizzical", "conundrum", "efflorescence",
    "luminous", "serene", "magnanimous", "lackadaisical", "catastrophe",
    "iridescence", "sensational", "melancholy", "captivate", "exuberant",
    "fascinate", "enigmatic", "magnificent", "effervescence", "breathtaking",
    "evanescent", "mellifluous", "capricious", "resilient", "effulgent",
    "quintessential", "bewilder", "vivacious", "nurturing", "effervescent",
    "serendipity", "phenomenal", "cynosure", "grandiose", "iridescent",
    "resplendence", "effulgence", "petrichor", "perpendicular", "astounding",
    "diaphanous", "whimsical", "buccaneer", "glorious", "incandescent",
    "swift", "bug", "program", "zephyr", "iridescent", "quintessential",
    "magnificent", "effulgence", "enigmatic", "mellifluous", "bucolic",
    "spectacular", "preposterous", "splendiferous", "jubilant", "effervescent",
    "iridescence", "sensational", "melancholy", "captivate", "exuberant",
    "fascinate", "enigmatic", "effervescence", "breathtaking", "evanescent",
    "mellifluous", "capricious", "resilient", "bewilder", "vivacious",
    "nurturing", "effervescent", "phenomenal", "cynosure", "iridescent",
    "resplendence", "effulgence", "perpendicular", "astounding", "diaphanous",
    "whimsical", "buccaneer", "glorious", "incandescent", "swift", "bug", "program",
    "exemplary", "belligerent", "indefatigable", "frivolous", "opulent" ,"abundance",
    "accolade", "adulation", "aesthetic", "altruism", "ameliorate",
    "amenable", "anachronistic", "antithesis", "aplomb", "apocryphal", "assuage",
    "audacious", "august", "auspicious", "banal", "behoove", "bellicose",
    "benevolent", "berate", "blithe", "bucolic", "cadence", "cajole", "callous",
    "candor", "capitulate", "catalyst", "caustic", "charlatan", "circumspect",
    "clairvoyant", "cogent", "complacent", "concord", "condone", "confluence",
    "congenial", "conundrum", "copious", "corpulent", "coterie", "cursory",
    "dauntless", "debacle", "decadence", "deferential", "deleterious", "demure",
    "denigrate", "deprecate", "derisive", "desultory", "diaphanous", "dichotomy",
    "diffident", "dilatory", "disparage", "divisive", "duplicity", "ebullient",
    "eclectic", "effervescent", "efficacious", "effusive", "egregious", "elicit",
    "eloquent", "elusive", "embezzle", "emollient", "empathy", "enigmatic",
    "ephemeral", "epiphany", "equanimity", "equivocate", "erudite", "esoteric",
    "euphemism", "evanescent", "exacerbate", "exculpate", "exemplary", "expedite",
    "extol", "facetious", "fallow", "fastidious", "feckless", "felicity",
    "flabbergast", "flippant", "florid", "foible", "fortuitous", "fractious",
    "frenetic", "furtive", "garrulous", "gregarious", "hackneyed", "hallowed",
    "hapless", "harangue", "hedonist", "heretic", "hubris", "idiosyncratic",
    "ignominious", "illustrious", "immutable", "impecunious", "imperturbable",
    "impervious", "impetuous", "implacable", "imprecation", "inane", "inchoate",
    "incessant", "inculcate", "indelible", "indolent", "ineffable", "inexorable",
    "ingenuous", "inimitable", "innocuous", "insidious", "insolent", "insouciant",
    "insurgent", "intrepid", "inveterate", "juxtapose", "kaleidoscope", "kowtow",
    "labyrinthine", "laconic", "languid", "lascivious", "laudatory", "lissome",
    "ludicrous", "lugubrious", "machiavellian", "magnanimous", "malaise",
    "malleable", "maverick", "mendacious", "mercurial", "meticulous", "misanthrope",
    "modicum", "monotonous", "mordant", "munificent", "myopic", "nefarious",
    "nihilism", "nondescript", "nonplussed", "nuance", "obdurate", "obfuscate",
    "oblivion", "obsequious", "obstreperous", "onus", "opulent", "ostensible",
    "overwrought", "paean", "palpable", "panacea", "paragon", "pariah",
    "parsimonious", "pedantic", "penchant", "perfunctory", "pernicious",
    "perspicacious", "pertinacious", "petulant", "platitude", "plethora",
    "polemic", "pragmatic", "precipitous", "prevaricate", "proclivity",
    "profound", "prosaic", "prurient", "pulchritudinous", "punctilious",
    "quagmire", "quandary", "querulous", "quixotic", "rancor", "rapacious",
    "recalcitrant", "reciprocal", "redolent", "replete", "reprobate", "rescind",
    "rhetoric", "sagacious", "salubrious", "sanctimonious", "sanguine", "sardonic",
    "sartorial", "scintillating", "scrupulous", "serendipity", "sibilant",
    "solipsistic", "soporific", "specious", "stalwart", "stentorian", "stipulate",
    "sublime", "sycophant", "taciturn", "tantamount", "tawdry", "temerity",
    "tenebrous", "tenuous", "timorous", "torpid", "trenchant", "truculent",
    "ubiquitous", "umbrage", "unctuous", "upbraid", "usurp", "vacuous", "vapid",
    "vehement", "venal", "veracity", "vicissitude", "vilify", "vitriolic",
    "vociferous", "wanton", "welter", "winsome", "wistful", "zealous"
]

